### ISSUE TITLE
Clicking on notification leaves a blank space

### ISSUE THREAD

**Issue by aravindparappil46** [setchy/atlassify#192]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

A blank space is left by the card which was most recently clicked/read.

### 🪜 Steps To Reproduce

1. Click on any notification
2. Notice that it will initiate the "swipe-right" animation
3. After the swipe animation, it leaves a blank space where the clicked notification was present originally i.e, the below notification items do not go up to fill this space

This behavior remains until you hide/show the accordion or hit `Cmd + R` to refresh. 

### Atlassify Version

1.3.1

### Operating System

macOS

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/f5410a15-cdf6-4dd1-9b62-4a604217acf7)

**Comment by setchy** [comment]
Thanks for reporting @aravindparappil46.

I was not able to reproduce on my machine with my account, but have seen this scenario before.

My theory is that the tailwind animation and API client call are both working, but the notification state removal is not leaving the orphaned empty row after notification interaction
https://github.com/setchy/atlassify/blob/26276b46c70639bf51d877549686667eae348031/src/renderer/utils/notifications/remove.ts#L7
